// Only a fixed diagnostic vocabulary is retained; values, URLs and identifiers are discarded.
const vocabulary=new Set('failed failure could not cannot unable establish connection connect signal signaling server reachable unreachable websocket socket closed close error timeout timed out ice rtcpeerconnection undefined unsupported browser worker create construct livekit frame metadata publish track media device permission denied unauthorized invalid token key origin negotiate negotiation offer answer session room client disconnected network fetch cancelled aborted transport handshake requires secure context read only property object function'.split(' '));
export function errorSignature(error){const text=String(error?.message||error||'').replace(/https?:\/\/[^\s]+|dct_[\w-]+|[\w-]{16,}\.[\w-]{16,}\.[\w-]{16,}/g,'');return (text.toLowerCase().match(/[a-z]+/g)||[]).filter(word=>vocabulary.has(word)).slice(0,35).join(' ');}
export function errorReason(error){const code=String(error?.code||'');if(['NotAllowedError','NotFoundError','NotReadableError','OverconstrainedError','SecurityError'].includes(error?.name))return 'camera';const msg=String(error?.message||error||'').toLowerCase();if(/worker/.test(msg))return 'worker';if(/\bice\b|ice[_ -](?:error|failed)/.test(msg+' '+code.toLowerCase()))return 'ice';if(/could not establish|unreachable|not reachable|network|fetch|negotiat|signal connection/.test(msg))return 'network';if(/origin/.test(msg))return 'origin';if(/unauthor|invalid.*key|auth|token|credential/.test(msg+' '+code.toLowerCase()))return 'auth';if(/quota|credit|balance|concurr/.test(msg))return 'credit';if(/model/.test(msg))return 'model';if(/websocket|socket/.test(msg))return 'socket';if(/timed? ?out|timeout/.test(msg))return 'timeout';if(/prompt|length|character/.test(msg))return 'prompt';return 'unknown';}
const session=crypto.randomUUID();
export function diagnostic(event,fields={}){const data={event,session,...fields};fetch('/api/diagnostics',{method:'POST',headers:{'Content-Type':'application/json','X-Anywear-Request':'1'},body:JSON.stringify(data),keepalive:true}).catch(()=>{});}
export function diagnosticError(event,error){const code=String(error?.code||'');diagnostic(event,{...(/^[A-Z_]{1,64}$/.test(code)?{code}:{}),reason:errorReason(error),signature:errorSignature(error)});}
export const sdkLogger=Object.fromEntries(['debug','info','warn','error'].map(level=>[level,(message,data)=>{const text=String(message);let phase;if(/frame-metadata/i.test(text))phase='worker';else if(/\bice\b|ice[_ -](?:error|failed)/i.test(text))phase='ice';else if(/websocket|socket/i.test(text))phase='socket';else if(/signaling/i.test(text))phase='signaling';else if(/livekit|room|media-channel/i.test(text))phase='media';else if(/credential|token/i.test(text))phase='credential';else if(/connect/i.test(text))phase='connect';else if(/image|prompt/i.test(text))phase='reference';else if(level==='error')phase='runtime';if(phase)diagnostic('sdk-'+level,{phase,...(['warn','error'].includes(level)?{reason:errorReason(data?.error||data?.message||message),signature:errorSignature(data?.error||data?.message||message)}:{})});}]));
export function sdkDiagnostic(event){const data=event.data;if(event.name==='client-session-connection-breakdown'){diagnostic('connection-breakdown',{success:data.success,durationMs:data.totalDurationMs,attempt:data.attempt});for(const p of data.phases||[]){const phase=String(p.phase).replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,48);diagnostic('connection-phase',{phase,success:p.success,durationMs:p.durationMs,...(p.error?{reason:errorReason(p.error)}:{})});}}else if(event.name==='reconnect'){diagnostic('reconnect',{success:data.success,durationMs:data.durationMs,attempt:data.attempt,...(data.error?{reason:errorReason(data.error)}:{})});}else if(event.name==='videoStall'){diagnostic('video-stall',{stalled:data.stalled,durationMs:data.durationMs});}}
