import {createDecartClient,models,resolveFpsNumber} from '@decartai/sdk';
import './style.css';
import {installI18n} from './i18n.js';
import {mountBilling,billing} from './billing.js';
import {diagnostic,diagnosticError,sdkLogger,sdkDiagnostic,errorReason} from './diagnostics.js';
import {SessionLane,stallAction,inputSize,drawRegion} from './session-model.js';
import {preferredCamera} from './camera-selection.js';
import {checkRealtimeSupport} from './realtime-support.js';
let realtimeSupport={ok:false,code:'WEBRTC_CHECKING'};
const $=id=>document.getElementById(id);
const lane=new SessionLane(),products=[],drafts=new Map(),images=new Map(),objectURLs=[];
let selected=null,viewIndex=0,category='all',config=null,source=null,feed=null,cameraEpoch=0,cameraPending=false,releaseLock=null;
let frameId=0,raf=0,lastCameraFrame=0,lastRemoteFrame=0,remoteFrameId=0,remoteRaf=0,remoteFrames=0,fpsStart=0;
let stalled=false;
let hasRemoteFrame=false,connectingAt=0,reconnectingAt=0,requestBusy=false,activeView='ai',sent=null,warningAt=0,sendState='待开始';
let permissionTimer=0,sessionTimer=0,limitNotice=0,stopRequested=false,connectionState='未连接',cameraState='未开启';
const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),rotatedCanvas=document.createElement('canvas'),rotatedCtx=rotatedCanvas.getContext('2d');
const currentView=()=>selected?.views?.[viewIndex];
const draftKey=()=>selected?selected.id+'|'+currentView().image:'';
const draftPrompt=()=>drafts.get(draftKey())??currentView()?.prompt??'';
const setText=(id,text)=>{$(id).textContent=text;};
const safeStorage={get(key){try{return localStorage.getItem(key);}catch{return null;}},set(key,value){try{localStorage.setItem(key,value);}catch{}}};
document.querySelector('#app').innerHTML=`
<header><a class="brand" href="/">anywear<span>●</span></a><span class="header-label">实时试衣间</span><span id="apiStatus" class="status">检查配置中</span></header>
<main>
<aside class="wardrobe"><div class="section-title"><h1>你的商品</h1><span id="productCount"></span></div>
<div class="tabs" role="tablist" aria-label="商品分类"><button data-category="all" role="tab" aria-selected="true">全部</button><button data-category="tops" role="tab" aria-selected="false">上衣</button><button data-category="bottoms" role="tab" aria-selected="false">裤子</button><button data-category="shoes" role="tab" aria-selected="false">鞋子 <small>实验</small></button><button data-category="accessories" role="tab" aria-selected="false">配件 <small>实验</small></button></div>
<div id="catalogMessage" class="note" role="status">加载本机商品…</div><div id="products" class="products"></div>
<section class="editor"><div class="section-title"><h2>准备应用</h2><button id="enlarge" class="text-button" disabled>查看大图</button></div><strong id="selectedName">—</strong><div id="referenceViews" class="reference-views"></div><p id="referenceNote" class="note"></p>
<details class="prompt-details" open><summary>试衣提示词 · Prompt <span id="promptState">草稿</span></summary><label class="sr-only" for="promptEditor">试衣提示词 · Prompt</label><textarea id="promptEditor" rows="6" spellcheck="false" disabled></textarea><div class="prompt-footer"><button id="resetPrompt" class="text-button">恢复默认</button><span id="promptLength"></span></div><p class="note">选图和编辑只更新草稿，点击应用才发送。活动会话在编辑时仍计费。</p></details></section>
<details class="upload-panel"><summary>上传其他商品</summary><label>上传品类 <select id="uploadCategory"><option value="tops">上衣</option><option value="bottoms">裤子</option><option value="shoes">鞋子（实验性）</option><option value="accessories">配件（实验性）</option><option value="outfit">整套穿搭（实验性）</option></select></label><button id="upload" class="secondary">＋ 上传图片</button><input id="file" type="file" accept="image/jpeg,image/png,image/webp" hidden><p class="note">单件、清晰、无人物的商品图更好。上传只保留在当前页面。</p></details>
<details class="help"><summary>接入与素材说明</summary><p>视频和选中参考图会发送至 Decart。本机摄影来自用户，未核验再分发许可，不进入公共仓库。每次发送单张图，不保证此前衣服保留；不做尺码测量。</p><a href="https://docs.platform.decart.ai/models/realtime/virtual-try-on" target="_blank" rel="noreferrer">官方接口说明 ↗</a></details>
</aside>
<section class="fitting"><div class="camera-toolbar"><label>摄像头 <select id="cameraSelect"><option value="">授权后选择摄像头</option></select></label><button id="refreshDevices" class="text-button">刷新设备</button><label>取景 <select id="framing"><option value="full">完整取景</option><option value="portrait">竖屏裁切</option></select></label><label>旋转 <select id="rotation"><option value="0">不旋转</option><option value="90">顺时针 90°</option><option value="270">逆时针 90°</option><option value="180">180°</option></select></label><label class="check-label"><input type="checkbox" id="mirrorDisplay">显示镜像</label></div>
<div class="stage"><div class="mirror full-frame"><video id="inputVideo" autoplay playsinline muted hidden></video><video id="output" autoplay playsinline muted hidden></video><div id="empty" class="empty"><h2>先预览，再试衣</h2><p>选择 iPhone 摄像头，检查光线和站位。</p><button id="previewCenter" class="primary">免费预览摄像头</button></div><div class="mirror-top"><span id="videoBadge">未开启</span><span id="shapeBadge">完整取景</span></div><div id="loading" class="loading" hidden><span class="spinner"></span><span id="loadingText"></span></div><div id="previewWrap" class="preview" hidden><video id="preview" autoplay playsinline muted></video><span>原画</span></div><div class="mirror-bottom"><span id="mirrorHint">保持上半身完整入镜</span></div></div></div>
<div class="session-bar"><div><small>已发送</small><strong id="sentName">—</strong></div><span id="applyStatus">待开始</span><div class="view-buttons"><button id="showAI" aria-pressed="true">AI</button><button id="showOriginal" aria-pressed="false">原画</button><button id="expandFitting" aria-expanded="false">放大试衣区</button><label><input id="pipToggle" type="checkbox" checked>小窗</label></div></div>
<div class="action-bar"><button id="previewOnly" class="secondary">免费预览</button><button id="start" class="primary" disabled>开始实时试衣</button><button id="stop" class="stop" disabled>结束</button></div>
<div class="live-summary"><span><small>本次估算</small> <strong id="liveCost">$0.0000</strong></span><span id="liveDuration">0 s</span><span id="quality">标准模式</span><button id="billingToggle" class="text-button">费用与记录</button></div>
<div id="message" class="message" role="status" aria-live="polite">先免费预览，确认取景后开始。视频和商品图会发送至 Decart。</div>
<div class="diagnostics"><span id="cameraState">未开启</span><span id="connectionState">未连接</span><span id="metrics">—</span><button id="checkApi" class="text-button">检查 API</button></div>
<details class="camera-help"><summary>iPhone 摄像头连接指引</summary><p>锁定并固定 iPhone，后置镜头朝向你。在浏览器和 Mac 隐私设置中允许摄像头，再刷新设备。解锁、来电或暂停可能中断画面；结束后重新锁定并预览。关闭系统人像虚化、自动追踪等效果可避免取景变化。</p></details>
<video id="sourceVideo" autoplay playsinline muted class="source-video"></video>
</section></main>
<dialog id="imageDialog"><button id="closeImage" class="secondary">关闭</button><h2 id="imageTitle"></h2><img id="largeImage" alt="商品参考图"><p id="largePrompt" class="note"></p></dialog>`;
function message(text,error=false){setText('message',text);$('message').classList.toggle('error',error);}
function loading(show,text=''){ $('loading').hidden=!show;if(text)setText('loadingText',text);}
function setState(cameraText=cameraState,connectionText=connectionState){cameraState=cameraText;connectionState=connectionText;setText('cameraState',cameraState);setText('connectionState',connectionState);}
function renderProducts(){
 const list=products.filter(p=>category==='all'||p.category===category);$('products').replaceChildren(...list.map(p=>{const b=document.createElement('button');b.className='product';b.setAttribute('aria-pressed',String(selected?.id===p.id));const art=document.createElement('div');art.className='product-art';const img=document.createElement('img');img.src=p.views[p===selected?viewIndex:0].image;img.alt=p.name;art.append(img);if(['shoes','accessories'].includes(p.category)){const badge=document.createElement('span');badge.className='product-badge';badge.textContent='实验性';art.append(badge);}const name=document.createElement('strong');name.textContent=p.name;const detail=document.createElement('small');detail.textContent=p.detail;b.append(art,name,detail);b.onclick=()=>select(p);return b;}));
 setText('productCount',String(products.length));
 if(!selected)return;setText('selectedName',selected.name);$('promptEditor').disabled=false;$('enlarge').disabled=false;
 $('referenceViews').replaceChildren(...selected.views.map((v,i)=>{const b=document.createElement('button');b.textContent=v.label;b.className='secondary';b.setAttribute('aria-pressed',String(i===viewIndex));b.onclick=()=>{viewIndex=i;renderProducts();showDraft();};return b;}));$('referenceViews').hidden=selected.views.length<2;
 setText('referenceNote',selected.views.length>1?'正反面分别应用单张图；背面不保证准确。':selected.category==='shoes'?'鞋类实验：需要双脚完整入镜。':selected.category==='accessories'?'配件实验：眼镜请让脸部清晰入镜，贴合与细节需实测。':'只替换所选品类，含模特原图的细节需要实测。');
 setText('mirrorHint',{tops:'保持上半身完整入镜',bottoms:'让腰部和双腿完整入镜',shoes:'鞋类实验 · 双脚完整入镜',accessories:selected.id==='local-meta2'?'眼镜实验 · 脸部清晰入镜':'配件实验 · 佩戴区域完整入镜',outfit:'整套实验 · 全身完整入镜'}[selected.category]);
}
function showDraft(){$('promptEditor').value=draftPrompt();updateDraftState();}
function updateDraftState(){const text=$('promptEditor').value;setText('promptLength',String(text.length));const same=sent&&selected?.id===sent.id&&currentView()?.image===sent.image&&text.trim()===sent.prompt;setText('promptState',same?'与已发送一致':'草稿 · 未发送');updateButtons();}
function select(p){selected=p;viewIndex=0;renderProducts();showDraft();}
function updateButtons(){const blocked=cameraPending||lane.pending||requestBusy;const live=!!lane.connection;const image=currentView();const ready=!!image&&images.get(image.image)?.ok===true&&!!$('promptEditor').value.trim();$('start').disabled=blocked||!ready||!realtimeSupport.ok||!config?.configured||(!feed&&!live);setText('start',live?'应用修改':'开始实时试衣');$('previewOnly').disabled=blocked||live;$('previewCenter').disabled=blocked;$('stop').disabled=!source&&!cameraPending&&!lane.pending&&!live;for(const id of ['cameraSelect','framing','rotation','refreshDevices'])$(id).disabled=blocked||live;$('showAI').disabled=!hasRemoteFrame;setText('applyStatus',sendState);}
async function preload(view){if(images.has(view.image))return images.get(view.image);try{const r=await fetch(view.image);if(!r.ok)throw Error();const blob=await r.blob();const bitmap=await createImageBitmap(blob);bitmap.close();const item={ok:true,blob};images.set(view.image,item);return item;}catch{const item={ok:false};images.set(view.image,item);return item;}}
async function loadCatalog(){try{const r=await fetch('/api/local-products');if(!r.ok)throw Error();const data=await r.json();products.push(...data.products);if(!products.length){setText('catalogMessage','本机未安装商品图。请将你的商品照片放入 src/local-products，或上传图片。');updateButtons();return;}select(products.find(p=>p.id==='local-pride')||products[0]);setText('catalogMessage','正在准备参考图…');await Promise.all(products.flatMap(p=>p.views.map(preload)));setText('catalogMessage',products.some(p=>p.views.some(v=>!images.get(v.image)?.ok))?'部分参考图加载失败，请检查文件后刷新。':'');$('catalogMessage').hidden=!$('catalogMessage').textContent;updateButtons();}catch{setText('catalogMessage','本机商品列表未加载，请重启本地服务。');}}
async function acquireLock(){if(releaseLock)return;if(!navigator.locks){throw Object.assign(Error(),{safeMessage:'请用新版 Chrome 打开，当前浏览器不支持单会话保护。'});}await new Promise((resolve,reject)=>{navigator.locks.request('anywear-active-camera',{ifAvailable:true},lock=>{if(!lock){reject(Object.assign(Error(),{safeMessage:'其他标签页正在使用试衣间，请先结束那个会话。'}));return;}return new Promise(release=>{releaseLock=release;resolve();});}).catch(reject);});}
function releaseIfIdle(){if(!source&&!cameraPending&&!lane.pending&&!lane.connection){releaseLock?.();releaseLock=null;}}
async function refreshDevices(preserveCurrent=true){if(!navigator.mediaDevices?.enumerateDevices)return;const devices=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='videoinput');const current=preserveCurrent?$('cameraSelect').value:'';const preferred=safeStorage.get('anywear-camera');$('cameraSelect').replaceChildren(...devices.map((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||'摄像头 '+(i+1);return o;}));const choice=preferredCamera(devices,current,preferred);if(choice)$('cameraSelect').value=choice.deviceId;else{const o=document.createElement('option');o.textContent='未发现摄像头';o.value='';$('cameraSelect').append(o);}return devices;}
function disposeCamera(){cameraEpoch++;if(frameId)$('sourceVideo').cancelVideoFrameCallback?.(frameId);cancelAnimationFrame(raf);source?.getTracks().forEach(t=>{t.onended=null;t.onmute=null;t.onunmute=null;t.stop();});source=null;feed?.getTracks().forEach(t=>t.stop());feed=null;for(const id of ['sourceVideo','inputVideo','preview'])$(id).srcObject=null;clearTimeout(permissionTimer);}
function syncFrameLayout(){document.querySelector('.mirror').classList.toggle('full-frame',$('framing').value==='full');setText('shapeBadge',$('framing').value==='portrait'?'9:16':'完整取景');}
function prepareFeed(){syncFrameLayout();feed?.getTracks().forEach(t=>t.stop());const v=$('sourceVideo'),mode=$('framing').value;const rotate=Number($('rotation').value);const swap=rotate===90||rotate===270;const size=inputSize(mode,swap?v.videoHeight:v.videoWidth,swap?v.videoWidth:v.videoHeight);canvas.width=size.width;canvas.height=size.height;const fps=resolveFpsNumber(models.realtime(config?.model||'lucy-vton-latest').fps);feed=canvas.captureStream(fps);$('inputVideo').srcObject=feed;$('preview').srcObject=feed;$('inputVideo').play().catch(()=>{});$('preview').play().catch(()=>{});setText('shapeBadge',mode==='portrait'?'9:16':'完整取景');return fps;}
function drawInput(){const v=$('sourceVideo');if(!v.videoWidth)return;let input=v,w=v.videoWidth,h=v.videoHeight;const angle=Number($('rotation').value);if(angle){const swap=angle===90||angle===270;rotatedCanvas.width=swap?h:w;rotatedCanvas.height=swap?w:h;rotatedCtx.save();rotatedCtx.translate(rotatedCanvas.width/2,rotatedCanvas.height/2);rotatedCtx.rotate(angle*Math.PI/180);rotatedCtx.drawImage(v,-w/2,-h/2);rotatedCtx.restore();input=rotatedCanvas;w=input.width;h=input.height;}const r=drawRegion($('framing').value,w,h,canvas.width,canvas.height);ctx.fillStyle='#121611';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(input,r.sx,r.sy,r.sw,r.sh,r.dx,r.dy,r.dw,r.dh);}
function watchSource(run){const v=$('sourceVideo');let previous=-1;const next=()=>{if(run!==cameraEpoch||!source)return;if(v.currentTime!==previous){previous=v.currentTime;lastCameraFrame=performance.now();drawInput();}if(v.requestVideoFrameCallback)frameId=v.requestVideoFrameCallback(next);else raf=requestAnimationFrame(next);};next();}
async function previewCamera(){if(cameraPending||lane.pending||lane.connection)return;cameraPending=true;const run=++cameraEpoch;updateButtons();loading(true,'等待摄像头授权…');setState('授权中');permissionTimer=setTimeout(()=>{if(run===cameraEpoch)message('请在浏览器和 Mac 设置中允许摄像头；可点击结束取消。');},30000);
 try{await acquireLock();if(run!==cameraEpoch)return;const model=models.realtime(config?.model||'lucy-vton-latest');const explicitChoice=$('cameraSelect').value||safeStorage.get('anywear-camera');await refreshDevices();if(run!==cameraEpoch)return;const choice=$('cameraSelect').value;let stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{...(choice?{deviceId:{exact:choice}}:{}),width:{ideal:model.width},height:{ideal:model.height},frameRate:model.fps}});if(run!==cameraEpoch){stream.getTracks().forEach(t=>t.stop());return;}source=stream;const v=$('sourceVideo');v.srcObject=stream;await v.play();if(run!==cameraEpoch)return;await refreshDevices(!!explicitChoice);if(run!==cameraEpoch)return;let actual=stream.getVideoTracks()[0].getSettings();const desired=$('cameraSelect').value;if(!explicitChoice&&desired&&desired!==actual.deviceId){stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{deviceId:{exact:desired},width:{ideal:model.width},height:{ideal:model.height},frameRate:model.fps}});if(run!==cameraEpoch){stream.getTracks().forEach(t=>t.stop());return;}source=stream;v.srcObject=stream;await v.play();if(run!==cameraEpoch)return;actual=stream.getVideoTracks()[0].getSettings();}if(actual.deviceId){$('cameraSelect').value=actual.deviceId;safeStorage.set('anywear-camera',actual.deviceId);}prepareFeed();lastCameraFrame=performance.now();watchSource(run);for(const t of source.getVideoTracks()){t.onended=()=>stop('摄像头已断开，请重新预览。',true);t.onmute=()=>{lastCameraFrame=Math.min(lastCameraFrame,performance.now()-5000);setState('摄像头暂停');};t.onunmute=()=>{lastCameraFrame=performance.now();setState('预览中');};}diagnostic('camera-ready',{mode:$('framing').value,width:canvas.width,height:canvas.height,fps:actual.frameRate||0,cameraWidth:actual.width||0,cameraHeight:actual.height||0,rotation:Number($('rotation').value)});setText('metrics','输入 '+canvas.width+'×'+canvas.height);setState('预览中');activeView='original';showVideo();message('免费预览已开启。确认画面和站位后，点击开始实时试衣。');}
 catch(e){if(run===cameraEpoch){diagnosticError('camera-error',e);disposeCamera();setState('摄像头失败');message(friendly(e),true);}}
 finally{clearTimeout(permissionTimer);cameraPending=false;loading(false);releaseIfIdle();updateButtons();}}
function showVideo(){const live=!!lane.connection||lane.pending;const original=!!feed&&(activeView==='original'||!hasRemoteFrame);$('inputVideo').hidden=!original;$('output').hidden=!hasRemoteFrame||original;$('empty').hidden=!!feed;$('previewWrap').hidden=!live||!hasRemoteFrame||original||!$('pipToggle').checked;setText('videoBadge',original?(live?'原画 · 会话仍计费':'免费摄像头预览'):hasRemoteFrame?'● AI 实时输出':'未开启');$('showAI').setAttribute('aria-pressed',String(activeView==='ai'));$('showOriginal').setAttribute('aria-pressed',String(activeView==='original'));}
function stopRemoteWatch(){if(remoteFrameId)$('output').cancelVideoFrameCallback?.(remoteFrameId);cancelAnimationFrame(remoteRaf);remoteFrameId=0;remoteRaf=0;}
function watchRemote(run){stopRemoteWatch();const v=$('output');let previous=-1;const next=()=>{if(!lane.current(run))return;if(v.currentTime!==previous&&v.readyState>=2){previous=v.currentTime;lastRemoteFrame=performance.now();remoteFrames++;if(!hasRemoteFrame){hasRemoteFrame=true;clearTimeout(sessionTimer);loading(false);billing.metric('firstFrameMs',Math.round(lastRemoteFrame-connectingAt));diagnostic('first-frame',{durationMs:Math.round(lastRemoteFrame-connectingAt)});fpsStart=lastRemoteFrame;remoteFrames=0;activeView='ai';showVideo();updateButtons();}if(lastRemoteFrame-fpsStart>=3000){const fps=remoteFrames/((lastRemoteFrame-fpsStart)/1000);setText('metrics','输出 '+fps.toFixed(1)+' fps · '+canvas.width+'×'+canvas.height);diagnostic('output-frames',{fps:Number(fps.toFixed(1)),width:v.videoWidth,height:v.videoHeight,durationMs:Math.round(lastRemoteFrame-fpsStart)});remoteFrames=0;fpsStart=lastRemoteFrame;}}if(v.requestVideoFrameCallback)remoteFrameId=v.requestVideoFrameCallback(next);else remoteRaf=requestAnimationFrame(next);};next();}
function requestSnapshot(){const view=currentView();const prompt=$('promptEditor').value.trim();if(!selected||!view||!images.get(view.image)?.ok){message('商品参考图未准备好，请检查文件后刷新。',true);return null;}if(!prompt){message('请填写提示词，或恢复默认提示词。',true);return null;}return {id:selected.id,name:selected.name,category:selected.category,image:view.image,view:view.label,prompt,enhance:false,blob:images.get(view.image).blob};}
function markSent(item){sent=item;setText('sentName',item.name);setText('sentView',item.view);sendState='参考图已发送';updateDraftState();}
async function applyOrStart(){if(requestBusy||lane.pending||cameraPending)return;const item=requestSnapshot();if(!item)return;if(lane.connection){const connection=lane.connection,run=lane.version;requestBusy=true;sendState='发送参考图…';updateButtons();const op=billing.operation(item),sentAt=performance.now();diagnostic('reference-send-start',{phase:item.category});try{await connection.set({image:item.blob,prompt:item.prompt,enhance:false});if(!lane.current(run))return;billing.operationEnd(op,'已发送');diagnostic('reference-send-end',{phase:item.category,success:true,durationMs:Math.round(performance.now()-sentAt)});markSent(item);message('参考图和提示词已发送，请观察 AI 中的实际变化。');}catch(e){diagnosticError('apply-error',e);diagnostic('reference-send-end',{phase:item.category,success:false,durationMs:Math.round(performance.now()-sentAt)});billing.operationEnd(op,'发送失败');if(lane.current(run)){sendState='发送失败';message(friendly(e),true);}}finally{if(lane.current(run)){requestBusy=false;updateButtons();}}return;}
 if(!feed){message('请先免费预览摄像头，再开始实时试衣。');return;}if(!config?.configured){message('后端未配置密钥，请配置 .env 后重启。',true);return;}
 const run=lane.begin();stopRequested=false;hasRemoteFrame=false;stalled=false;setText('debugCode','');sent=null;sendState='连接中';activeView='original';connectingAt=performance.now();diagnostic('connect-start',{model:config.model,mode:$('framing').value,width:canvas.width,height:canvas.height});fpsStart=connectingAt;remoteFrames=0;reconnectingAt=0;warningAt=0;setState('摄像头已就绪','连接中');loading(true,'连接中 · 等待 AI 首帧');updateButtons();billing.begin(config.model,{sdk:'0.2.7',mode:$('framing').value,inputWidth:canvas.width,inputHeight:canvas.height,camera:source.getVideoTracks()[0].getSettings()});const op=billing.operation(item);
 sessionTimer=setTimeout(()=>{if(lane.current(run)&&!hasRemoteFrame)stop('60 秒未收到 AI 首帧，已停止，请检查网络后重试。',true);},60000);
 try{const client=createDecartClient({apiKeyProvider:token,logger:sdkLogger});const connection=await client.realtime.connect(feed,{model:models.realtime(config.model),mirror:false,initialState:{image:item.blob,prompt:{text:item.prompt,enhance:false}},onRemoteStream:stream=>{if(!lane.current(run)){stream.getTracks().forEach(t=>t.stop());return;}$('output').srcObject=stream;$('output').play().catch(()=>message('AI 视频无法播放，请结束后重试。',true));for(const track of stream.getVideoTracks())track.onended=()=>{if(lane.current(run))stop('远端画面已结束，请重新开始。',true);};watchRemote(run);},onConnectionChange:state=>{if(!lane.current(run))return;diagnostic('connection-state',{state,durationMs:Math.round(performance.now()-connectingAt)});billing.state(state);const labels={connecting:'连接中',connected:'已连接',generating:'生成中',reconnecting:'重连中',disconnected:'已断开'};setState(cameraState,labels[state]||state);if(state==='reconnecting'){reconnectingAt=performance.now();hasRemoteFrame=false;stopRemoteWatch();activeView='original';showVideo();loading(true,'网络波动，正在重连…');}else if(state==='connected'||state==='generating'){reconnectingAt=0;if($('output').srcObject)watchRemote(run);}else if(state==='disconnected'&&!lane.pending){stop('连接已断开，请重新预览和开始。',true);}},onConnectionQuality:report=>{if(lane.current(run))setText('quality',({good:'网络良好',fair:'网络一般',poor:'网络较差',critical:'网络不稳定'}[report.quality]||'网络待检查'));},onQueuePosition:q=>{if(lane.current(run)){setState(cameraState,'排队中');loading(true,'排队中 · '+q.position);}}});
 if(!lane.resolve(run,connection)){billing.operationEnd(op,'取消待核对');return;}
 connection.on('diagnostic',sdkDiagnostic);connection.on('generationTick',data=>{if(lane.current(run))billing.report(data.seconds);});connection.on('generationEnded',data=>{if(lane.current(run))billing.report(data.seconds);});connection.on('sessionEnded',()=>{if(lane.current(run))stop('Decart 已结束会话，可以重新预览。');});connection.on('error',e=>{diagnosticError('sdk-error',e);if(lane.current(run))message(friendly(e),true);});connection.on('stats',s=>{if(lane.current(run))billing.stats(s);});
 billing.operationEnd(op,'已发送');markSent(item);showVideo();limitNotice=setTimeout(()=>{if(lane.current(run))message('本次试衣即将达到 5 分钟上限。');},Math.max(0,config.maxSessionSeconds-30)*1000);setTimeoutGuard(run,config.maxSessionSeconds);message('实时连接已建立。参考图已发送，请观察换装并小幅运动。');
 }catch(e){diagnosticError('connect-error',e);lane.reject();billing.operationEnd(op,'连接失败');if(lane.current(run))stop(friendly(e),true);}
 finally{if(stopRequested){setState('已关闭','已结束');sendState='待开始';billing.end('取消待核对');}releaseIfIdle();updateButtons();}}
let maxTimer=0;function setTimeoutGuard(run,seconds){maxTimer=setTimeout(()=>{if(lane.current(run))stop('已达到本次时长上限，会话已停止。');},seconds*1000);}
function stop(text='会话已结束，摄像头已关闭。',error=false){diagnostic('stop',{state:error?'failed':'ended',reason:lane.pending?'cancelled':'unknown'});stopRequested=true;const wasPending=lane.pending;lane.cancel();clearTimeout(sessionTimer);clearTimeout(maxTimer);clearTimeout(limitNotice);stopRemoteWatch();disposeCamera();hasRemoteFrame=false;reconnectingAt=0;requestBusy=false;$('output').srcObject=null;loading(false);activeView='original';sent=null;setText('sentName','—');setText('sentView','');sendState=wasPending?'停止处理中':'待开始';setState('已关闭',wasPending?'停止处理中':'已结束');setText('metrics','—');setText('quality','标准模式');stalled=false;showVideo();billing.end(error||wasPending?'中断待核对':'已结束');releaseIfIdle();updateButtons();message(text,error);}
async function token(){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{const res=await fetch('/api/token',{method:'POST',headers:{'X-Anywear-Request':'1'},signal:controller.signal});const data=await res.json();if(!res.ok)throw Object.assign(Error(),{safeMessage:data.error});return data.apiKey;}finally{clearTimeout(timeout);}}
function friendly(e){if(/rtcpeerconnection.*unsupported|webrtc.*unsupported/i.test(String(e.message||'')))return '当前浏览器不支持实时视频，请用 Mac 的 Chrome 或 Safari 打开 localhost:3000。';if(e.safeMessage)return e.safeMessage;const cameraErrors={NotAllowedError:'摄像头权限被拒绝，请在浏览器和 Mac 设置中允许后重试。',NotFoundError:'未发现摄像头，请连接后刷新设备。',NotReadableError:'摄像头无法读取，请关闭占用摄像头的应用。',OverconstrainedError:'所选摄像头不可用，请刷新设备并重新选择。',AbortError:'请求超时或已取消，请重试。'};if(cameraErrors[e.name])return cameraErrors[e.name];const reason=errorReason(e);if(reason==='worker')return '视频连接组件启动失败，已记录日志，请等待修复后重试。';if(reason==='network')return '实时视频连接失败，服务器未能建立视频通道。已记录日志，请结束后重试。';const code=String(e.code||'');setText('debugCode',/^[A-Z_]{1,64}$/.test(code)?code:'');if(/PROMPT|TEXT|LENGTH/.test(code)||code==='INVALID_INPUT'&&/prompt|length|character|token/i.test(String(e.message||'')))return '提示词过长或不符合接口要求，请缩短后重新应用。';if(/AUTH|TOKEN|KEY/.test(code))return 'Decart 身份验证失败，请检查密钥和权限。';if(/QUOTA|LIMIT|CREDIT/.test(code))return 'Decart 额度或并发不足，请检查账户。';return '操作失败，请检查网络、摄像头和账户后重试。';}
// Draft editing never sends network updates. Only an explicit click snapshots the request.
$('promptEditor').oninput=()=>{drafts.set(draftKey(),$('promptEditor').value);updateDraftState();};$('resetPrompt').onclick=()=>{drafts.delete(draftKey());showDraft();};
$('start').onclick=applyOrStart;$('stop').onclick=()=>stop();$('previewOnly').onclick=previewCamera;$('previewCenter').onclick=previewCamera;
$('cameraSelect').onchange=async()=>{safeStorage.set('anywear-camera',$('cameraSelect').value);if(source){disposeCamera();await previewCamera();}};
$('refreshDevices').onclick=()=>refreshDevices().then(()=>message('设备列表已刷新。')).catch(()=>message('无法获取设备列表，请先允许摄像头。',true));
const updateFraming=()=>{syncFrameLayout();if(source){prepareFeed();drawInput();showVideo();setText('metrics','输入 '+canvas.width+'×'+canvas.height);}};
$('framing').onchange=updateFraming;$('rotation').onchange=()=>{safeStorage.set('anywear-rotation',$('rotation').value);updateFraming();};
$('rotation').value=safeStorage.get('anywear-rotation')||'0';
$('mirrorDisplay').onchange=()=>document.querySelector('.mirror').classList.toggle('display-mirrored',$('mirrorDisplay').checked);
function expandFitting(expanded){document.querySelector('.fitting').classList.toggle('expanded',expanded);document.body.classList.toggle('fitting-expanded',expanded);$('expandFitting').setAttribute('aria-expanded',String(expanded));setText('expandFitting',expanded?'退出大图':'放大试衣区');}
$('billingToggle').addEventListener('click',()=>expandFitting(false));
$('expandFitting').onclick=()=>expandFitting($('expandFitting').getAttribute('aria-expanded')!=='true');document.addEventListener('keydown',e=>{if(e.key==='Escape')expandFitting(false);});
$('showAI').onclick=()=>{activeView='ai';showVideo();};$('showOriginal').onclick=()=>{activeView='original';showVideo();};$('pipToggle').onchange=showVideo;
$('checkApi').onclick=async()=>{$('checkApi').disabled=true;try{createDecartClient({apiKeyProvider:token});await token();setText('apiStatus','API 令牌验证通过');message('令牌验证通过，尚未开启生成会话。');}catch(e){setText('apiStatus','API 验证失败');message(friendly(e),true);}finally{$('checkApi').disabled=false;}};
for(const b of document.querySelectorAll('[data-category]'))b.onclick=()=>{category=b.dataset.category;for(const t of document.querySelectorAll('[data-category]'))t.setAttribute('aria-selected',String(t===b));renderProducts();};
$('enlarge').onclick=()=>{if(!selected)return;setText('imageTitle',selected.name);$('largeImage').src=currentView().image;setText('largePrompt',currentView().label);$('imageDialog').showModal();};$('closeImage').onclick=()=>$('imageDialog').close();$('imageDialog').onclick=e=>{if(e.target===$('imageDialog'))$('imageDialog').close();};
$('upload').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10*1024*1024)throw Error();const bitmap=await createImageBitmap(f);const min=Math.min(bitmap.width,bitmap.height);bitmap.close();const c=$('uploadCategory').value,url=URL.createObjectURL(f);objectURLs.push(url);const region={tops:'upper body garment',bottoms:'lower body garment',shoes:'footwear',outfit:'outfit'}[c];const p={id:crypto.randomUUID(),name:f.name.replace(/\.[^.]+$/,''),category:c,detail:'本次页面上传',views:[{label:'商品参考',image:url,prompt:c==='accessories'?'Add the accessory shown in the reference image to its natural wearing position on the person, matching its visible color, shape and details. Preserve the camera subject, existing clothing and background.':`Substitute the ${region} with the clothing in the reference image, matching its visible color, shape and details. Preserve the camera subject and background.`}]};images.set(url,{ok:true,blob:f});products.unshift(p);category='all';document.querySelector('[data-category=all]').click();select(p);if(min<512)message('图片清晰度较低，建议使用至少 512px 的参考图。');}catch{message('请上传有效且不超过 10MB 的 JPEG、PNG 或 WebP。',true);}finally{e.target.value='';}};
// Watch actual decoded source frames, not repeated canvas draws.
setInterval(()=>{if(!source||document.hidden)return;const now=performance.now();const sourceAge=now-lastCameraFrame,remoteAge=hasRemoteFrame?now-lastRemoteFrame:0;const action=stallAction(Math.max(sourceAge,remoteAge),true);if(action==='stop'){stop('画面已停滞 15 秒，会话已停止，请重新预览。',true);return;}if(action==='none'&&stalled){stalled=false;showVideo();message('画面已恢复。');}if(action==='warn'&&now-warningAt>5000){warningAt=now;stalled=true;setText('videoBadge','画面异常 · 检查连接');message('超过 5 秒没有新画面，请检查 iPhone 是否暂停或网络中断。',true);}if(reconnectingAt&&now-reconnectingAt>=30000)stop('重连超过 30 秒，已停止，请重新开始。',true);},1000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden){lastCameraFrame=performance.now();lastRemoteFrame=performance.now();}});
navigator.mediaDevices?.addEventListener('devicechange',()=>{if(!lane.connection&&!lane.pending)refreshDevices().catch(()=>{});});
window.addEventListener('pagehide',()=>{stop();objectURLs.forEach(URL.revokeObjectURL);});
const debugCode=document.createElement('span');debugCode.id='debugCode';document.querySelector('.diagnostics').append(debugCode);
const sentView=document.createElement('small');sentView.id='sentView';$('sentName').after(sentView);
mountBilling();installI18n();
const browserNote=document.createElement('p');browserNote.className='browser-note';browserNote.textContent='正在检查浏览器实时视频能力…';document.querySelector('.camera-toolbar').after(browserNote);checkRealtimeSupport().then(result=>{realtimeSupport=result;browserNote.textContent=result.ok?'浏览器实时视频能力检查通过':'当前浏览器不支持实时视频，请用 Mac 的 Chrome 或 Safari 打开 localhost:3000。';diagnostic('browser-capability',{success:result.ok,code:result.code});updateButtons();});
Promise.all([fetch('/api/status').then(r=>r.json()).then(data=>{config=data;setText('apiStatus',data.configured?'密钥已配置':'密钥未配置');updateButtons();}).catch(()=>message('本地后端无法连接，请重启服务。',true)),loadCatalog()]);
